### ISSUE TITLE
openai version is not getting updated to a new one 'for some reason'.

### ISSUE THREAD

**Issue by gkaleta** [Azure/intro-to-intelligent-apps#28]
![image](https://github.com/Azure/intro-to-intelligent-apps/assets/22896482/095d4ee0-1e6c-426d-96aa-6c628072aff1)

This wont allow Lab 02 - get available model deploys will fail due to inconsistency

**Comment by kevingbb** [comment]
@gkaleta, can you please elaborate. The get models api has nothing to do with a deployment or its version, it is a rest-based API version that matters.
