### ISSUE TITLE
.NET interactive notebooks need .NET 7.0

### ISSUE THREAD

**Issue by jometzg** [Azure/intro-to-intelligent-apps#9]
Python notebooks work. But .NET ones now require .NET 7, when only .NET 6 is in the dev container.

I have suggested to change:
1. In docker-compose.yml line 13 to "VARIANT: 7.0.jammy"
2. In Dockerfile line 3 tp ARG VARIANT="7.0.jammy"

Works for me.

Would do a pull request if I knew how :-)

**Comment by MarkWme** [comment]
Create a branch, make your changes, commit and create a PR 😎 

Happy to walk you through it.

**Comment by MarkWme** [comment]
Hey @jometzg - as you're not around this week, I've made the above changes.
